name: ns-create-webhook

on:
  repository_dispatch:
    types: [ns-create-webhook]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Webhook triggered!"

      - name: Print payload
        run: echo "${{ github.event.client_payload.message }}"        